### ISSUE TITLE
"PREFIX"

### ISSUE THREAD

**Issue by realmayus** [Snapecraft-Serverteam/CustomLobby-v2#3]
![](https://i.imgur.com/2cLeo5I.png)

**Comment by Tallerik** [comment]
lol

**Comment by Tallerik** [comment]
Welcher befehl ist das?

**Comment by realmayus** [comment]
Ich meine das war /fly

aber: eine einheitliche fehlermeldung wäre leckerer

**Comment by Tallerik** [comment]
Klar schau ich demnächst drüber

**Comment by Tallerik** [comment]
#IstImTrello

**Comment by realmayus** [comment]
Noch nicht das Github-trello gesehen?

**Comment by Tallerik** [comment]
Das ist kein Fehler im Code die prefix wurde nicht aus der config geladen. Ist warscheinlich durch Neustart behoben.

**Comment by realmayus** [comment]
👍
